### ISSUE TITLE
Can we configure logStream in Nlog.Config file? As because I see it create new files in logGroup for every request

### ISSUE THREAD

**Issue by ckvnahsik** [aws/aws-logging-dotnet#92] opened 2019-07-10 08:46 UTC

**Comment by klaytaybai** [comment] 2019-07-11 21:34
Hi @ckvnahsik, this is in a way a duplicate of https://github.com/aws/aws-logging-dotnet/issues/1.  You'll find more discussion there about this topic.

**Closed** 2019-07-11 21:34 UTC
Labels: duplicate
