### ISSUE TITLE
Add option to include category name in logged message

### ISSUE THREAD

**Issue by Herdo** [aws/aws-logging-dotnet#45] opened 2018-05-01 22:27 UTC
When resolving an `ILogger<TCategoryName>`, the category name should be included in the logged message. This can be a default (as it is in the `ConsoleLogger`), but an opt-in would be OK, too.

**Comment by normj** [comment] 2018-07-03 23:21
I like the idea but I would favor an opt-in to not surprise existing users.

**Comment by qidydl** [comment] 2019-04-26 15:32
The category name and log level are pretty standard metadata I would expect to see included with each log event.

**Comment by qidydl** [comment] 2019-04-26 15:33
I think this is a duplicate of #23.

**Comment by normj** [comment] 2019-06-26 07:14
I have created PR https://github.com/aws/aws-logging-dotnet/pull/90 that will add support for category name.

**Comment by normj** [comment] 2019-06-27 21:59
In version 2.0.0 of AWS.Logger.AspNetCore you can set the `IncludeCategory` to true in your appsettings.json and then event id will be included in the log message.

https://github.com/aws/aws-logging-dotnet/blob/master/RELEASE.CHANGELOG.md#release-2019-06-27

**Closed by normj** 2019-06-27 21:59 UTC
Labels: feature-request
